server:
    port: 9092
spring:
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
            auto-commit: true
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASS}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect